version: '3'

services:
  vite:
    build:
      context: ./
      dockerfile: Dockerfile

    working_dir: /usr/cf
    ports:
      - "5433:5433"
    expose:
      - 5433
    volumes:
      - .:/usr/cf
      - /usr/cf/node_modules
    
