version: '3'

services:
  vite:
    build:
      context: ./
      dockerfile: Dockerfile

    working_dir: /usr/cf
    ports:
      - "5432:5432"
    expose:
      - 5432
    volumes:
      - .:/usr/cf
      - /usr/cf/node_modules
    
